m4: Fix 32bit build with 64bit version of libunwind-dev installed.
32 and 64 bit versions of libunwind-dev package can not be installed
at the same time at least in Debian and Ubuntu.  AC_CHECK_LIB macro
doesn't know if we have '-m32' in OVS_CFLAGS, so we need to
additionally check for actual compiling possibility before enabling
the feature.  Otherwise 'make' will fail due to inability to
build with 64bit libunwind headers:

    https://travis-ci.org/openvswitch/ovs/jobs/590580374

    /usr/include/libunwind.h:23:28: fatal error:
        libunwind-x86.h: No such file or directory

CC: William Tu <u9012063@gmail.com>
Fixes: e2ed6fbeb18c ("fatal-signal: Catch SIGSEGV and print backtrace.")
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>